/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // KisanRaw sovereign brand palette (login gateway)
        brand: {
          50: '#ecfdf5',
          100: '#d1fae5',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
          950: '#022c22',
        },
        govslate: {
          850: '#141e2e',
          900: '#0f172a',
        },
        // Material Design 3 operational token system (dashboard pages)
        outline: '#707974',
        'tertiary-container': '#004870',
        'on-secondary-fixed': '#2f1500',
        'on-tertiary-fixed': '#001d31',
        'surface-tint': '#2b6954',
        'on-primary-fixed': '#002117',
        'on-surface-variant': '#404944',
        'secondary-fixed-dim': '#ffb77d',
        'primary-fixed': '#b0f0d6',
        'secondary-container': '#fe932c',
        primary: '#003527',
        'on-background': '#0d1c2f',
        'inverse-on-surface': '#ebf1ff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        background: '#f8f9ff',
        'primary-fixed-dim': '#95d3ba',
        'on-surface': '#0d1c2f',
        'primary-container': '#064e3b',
        'on-error': '#ffffff',
        tertiary: '#00314e',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#004b73',
        'surface-container-highest': '#d5e3fd',
        'on-primary': '#ffffff',
        'on-primary-container': '#80bea6',
        'on-secondary-container': '#663500',
        'surface-container-high': '#dde9ff',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed-dim': '#93ccff',
        'surface-container-low': '#eff4ff',
        secondary: '#904d00',
        'secondary-fixed': '#ffdcc3',
        'on-error-container': '#93000a',
        'surface-dim': '#ccdbf4',
        'on-tertiary-container': '#5db9ff',
        'inverse-surface': '#233144',
        'on-primary-fixed-variant': '#0b513d',
        'surface-container-lowest': '#ffffff',
        surface: '#f8f9ff',
        'on-secondary-fixed-variant': '#6e3900',
        'inverse-primary': '#95d3ba',
        'outline-variant': '#bfc9c3',
        'error-container': '#ffdad6',
        'surface-variant': '#d5e3fd',
        'tertiary-fixed': '#cce5ff',
        'surface-container': '#e6eeff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        gutter: '1rem',
        'space-lg': '1rem',
        'space-md': '0.75rem',
        'space-xl': '1.5rem',
        margin: '1rem',
      },
      fontFamily: {
        sans: ['"Public Sans"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        'label-md': ['Inter'],
        'data-mono': ['Inter'],
        'body-sm': ['Inter'],
        'body-lg': ['Inter'],
        'headline-sm': ['Public Sans'],
        'body-md': ['Inter'],
        'headline-md': ['Public Sans'],
        'headline-xl': ['Public Sans'],
        'label-lg': ['Inter'],
        'label-sm': ['Inter'],
        'headline-lg': ['Public Sans'],
      },
      fontSize: {
        'label-md': ['11px', { lineHeight: '14px', fontWeight: '600' }],
        'data-mono': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-sm': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-xl': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        'label-lg': ['13px', { lineHeight: '16px', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '12px', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '30px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
